# Generated by Django 2.0.4 on 2018-04-12 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_title', models.CharField(max_length=20)),
                ('d_content', models.CharField(max_length=1000)),
                ('d_location', models.CharField(max_length=200)),
                ('d_ispublic', models.CharField(choices=[('0', '仅自己'), ('1', '所有人')], max_length=2)),
            ],
            options={
                'db_table': 'diary',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='d_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripdiary.User'),
        ),
        migrations.AddField(
            model_name='credit',
            name='c_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripdiary.User'),
        ),
        migrations.AddField(
            model_name='credit',
            name='c_diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripdiary.Diary'),
        ),
    ]
