# Generated by Django 2.0.4 on 2018-05-08 09:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0002_auto_20180506_2104'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diary',
            managers=[
                ('maneger', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='diary',
            name='d_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='d_title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
