# Generated by Django 2.0.4 on 2018-05-09 01:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0003_auto_20180508_1741'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='diary',
            managers=[
                ('manager1', django.db.models.manager.Manager()),
            ],
        ),
    ]
