# Generated by Django 2.0.4 on 2018-05-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0004_auto_20180509_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to='upload')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
