# Generated by Django 2.0.4 on 2018-05-13 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0005_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='c_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
