# Generated by Django 2.0.4 on 2018-05-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0006_auto_20180513_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='d_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
