# Generated by Django 2.0.4 on 2018-05-13 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0008_auto_20180513_1015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
        migrations.AlterField(
            model_name='credit',
            name='c_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diary',
            name='d_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
