# Generated by Django 2.0.4 on 2018-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0009_auto_20180513_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='d_date',
            field=models.CharField(max_length=50),
        ),
    ]
