# Generated by Django 2.0.4 on 2018-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0010_auto_20180514_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='d_title',
            field=models.CharField(max_length=20),
        ),
    ]
