# Generated by Django 2.0.4 on 2018-05-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0011_auto_20180515_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='c_date',
            field=models.CharField(max_length=50),
        ),
    ]
