# Generated by Django 2.0.4 on 2018-05-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0012_auto_20180516_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='credit',
            table='credit',
        ),
    ]
