# Generated by Django 2.0.4 on 2018-05-16 08:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0013_auto_20180516_1050'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='credit',
            managers=[
                ('manager2', django.db.models.manager.Manager()),
            ],
        ),
    ]
