# Generated by Django 2.0.4 on 2018-05-23 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0014_auto_20180516_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-c_date']},
        ),
    ]
