# Generated by Django 2.0.4 on 2018-05-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0015_auto_20180523_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='d_content',
            field=models.CharField(max_length=10000),
        ),
    ]
