# Generated by Django 2.0.4 on 2018-05-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripdiary', '0018_auto_20180528_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['c_date']},
        ),
    ]
